# Generated by Django 5.0.8 on 2025-05-31 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryTitle', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'FoodCategory',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('foodCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resturant.foodcategory')),
            ],
            options={
                'verbose_name_plural': 'Food',
            },
        ),
    ]
