# Generated by Django 5.0.8 on 2025-05-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=50)),
                ('roomDescription', models.CharField(max_length=200)),
                ('costPerNight', models.FloatField()),
                ('discount_percent', models.FloatField()),
            ],
        ),
    ]
