# Generated by Django 5.0.8 on 2025-05-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtypes',
            options={'verbose_name_plural': 'RoomTypes'},
        ),
    ]
